Repository django-notifications/django-notifications, pull requests merged in 2023-05, with the labels that each got.

#287 [models] Added method to return links to related objects.
  notifications/admin.py
  notifications/base/models.py
Labels: enhancement, version 1.8.0

#320 allow to set target proxy objects
  notifications/base/models.py
Labels: enhancement, version 1.8.0

#361 Fix #312
  notifications/apps.py
Labels: bug, version 1.8.0

#352 [feat] add caching and a setting CACHE_TIMEOUT to configure the timeout
  CHANGELOG.rst
  notifications/settings.py
  notifications/templatetags/notifications_tags.py
Labels: enhancement, waiting for feedback
